### ISSUE TITLE
Missing semicolons.

### ISSUE THREAD

**Issue by whitneyit** [WolfgangKluge/postcss-media-variables#1]
In the [min-width in sub-decl.output.css](https://github.com/WolfgangKluge/postcss-media-variables/blob/master/test/assets/min-width%20in%20sub-decl.output.css#L3) spec you are leaving off a semi colon.

I discovered this whilst tracking down another issue *extra new lines between rules* I'm not sure if that is related to this.

Cheers

**Comment by WolfgangKluge** [comment]
Thanks for reporting.

I tracked this issue down to [`node.removeSelf()`](https://github.com/postcss/postcss/blob/master/docs/api.md#user-content-noderemoveself).

Maybe it has something to do with the `clone` method ([currently, `clone` does not return an exact copy of a node](https://github.com/postcss/postcss/issues/364)). But I have to investigate it further.

**Comment by WolfgangKluge** [comment]
Fixed it by using `moveTo` instead of `replaceWith`.
It seems that internally, `replaceWith` uses a `clone` of the new node and thus its style is cleaned.

`moveTo` also changes some style (e.g. it uses the indentation of the parent), but only of the node about to move, not it's children.

**Comment by whitneyit** [comment]
Awesome. Thanks mate
