### ISSUE TITLE
Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.14, but postcss-media-variables us es 6.0.23. 

### ISSUE THREAD

**Issue by maystrenkoYurii** [WolfgangKluge/postcss-media-variables#12]
Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.14, but postcss-media-variables us es 6.0.23.

**Comment by joshwcorbett** [comment]
This plugin hasn't been updated in 4 years, not confident that this plugin is going to be updated any time soon.
