### ISSUE TITLE
Use properties for different stages of running

### ISSUE THREAD

**Issue by MadLittleMods** [WolfgangKluge/postcss-media-variables#4]
Use properties for different stages of running to avoid confusion and add more composibility, flexibility: `mediaVariables.inspect()` and `mediaVariables.resolve()`

``` js
var postcss = require('postcss');

var mediaVariables = require('postcss-media-variables');

var mycss = fs.readFileSync('input.css', 'utf8');

// Process your CSS
var output = postcss([
        mediaVariables.inspect(), // first run
       // ...
        mediaVariables.resolve() // second run
    ])
    .process(mycss)
    .css;

console.log(output);
```

**Comment by WolfgangKluge** [comment]
I like the idea, but I see no chance to get it working while being backward compatible since `mediaVariables` still have to be a `postcss.plugin(..)`
