### ISSUE TITLE
Tests pass but I am getting `::-postcss-media-variables` in output

### ISSUE THREAD

**Issue by MadLittleMods** [WolfgangKluge/postcss-media-variables#5]
I am trying to use this with PostCSS v5 before the upgrade (should work, just deprecated method warnings).

I ran the tests on this repo and they pass but when I try to use this plugin, it keeps `::-postcss-media-variables` bugs in the output. It seems to happen whether I run the other plugins in the stack or not.

``` json
"devDependencies": {
    "postcss": "^5.0.6",
    "postcss-calc": "^5.0.0",
    "postcss-css-variables": "^0.5.0",
    "postcss-custom-media": "^5.0.0",
    "postcss-import": "^7.0.0",
    "postcss-media-variables": "^1.1.2"
}
```

``` js
'use strict';

let postcss = require('postcss');
let mediaVariables = require('postcss-media-variables');

let cssVariables = require('postcss-css-variables');
let calc = require('postcss-calc');
let customMedia = require('postcss-custom-media');

let warningToString = function(warning) {
    return warning.type + ': ' + warning.text;
};


let processor = postcss(
    mediaVariables(),
    /* */
    customMedia(),
    cssVariables(),
    calc(),
    /* */
    mediaVariables()
);

let input = `
:root {
    --min-width: 1000px;
}
@media (max-width: calc(var(--min-width) - 1px)) {}
`;

processor
    .process(input)
    .then(function (result) {
        let output = result.css;
        let warnings = result.warnings().map(warningToString).join('\n\n');

        console.log(output);
    });


```

**Comment by WolfgangKluge** [comment]
Thanks for investigation..
Hmm, I've no idea, though I can reproduce it..?

It seems like

```js
var stepNode = postcss.decl({
    prop: runProperty,
    value: '0'
});

stepNode.value = "1";
```

has no impact in the next run where I search for this decl in every rule - but if I try to reduce my code to just this case, it works...
I'll try it again, later :)

If I use the new version, there's no problem anymore.. Could you please confirm..

**Comment by MadLittleMods** [comment]
@WolfgangKluge I still have many problems with v2

**Comment by letops** [comment]
Hi:

I am having problems as well, I use the following PostCSS config in combination with ExtractText from Webpack. I am having the exact same problem with the `::-postcss-media-variables` selector inside the CSS. I hope this helps to find the possible bug

    module.exports = {
      plugins: [
        require('postcss-partial-import')({ extension: '.pcss' }),
        require('postcss-media-variables'),
        require('postcss-flexbugs-fixes'),
        require('postcss-custom-media'),
        require('postcss-mixins'),
        require('postcss-simple-vars'),
        require('postcss-nested'),
        require('postcss-grid-kiss'),
        require('postcss-calc'),
        require('postcss-cssnext'),
        require('postcss-custom-properties'),
        require('postcss-media-variables'),
        require('postcss-color-function'),
        require('postcss-will-change'),
        require('postcss-vertical-rhythm'),
        require('postcss-minify-selectors'),
        require('postcss-minify-params'),
        require('postcss-font-smoothing'),
        require('postcss-normalize'),
      ]
    }

**Comment by WolfgangKluge** [comment]
I can't reproduce the issue at the moment.
Can you provide a small example of CSS and remove all unnecessary config lines (unnecessary for this bug)?

PR welcome 😀
